return {
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/which-key.nvim", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "folke/neodev.nvim", enabled = false },
  { "hrsh7th/cmp-buffer", enabled = false },
}
